/*-
 * #%L
 * athena-cloudwatch
 * %%
 * Copyright (C) 2019 Amazon Web Services
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package com.amazonaws.athena.connectors.cloudwatch;

import com.amazonaws.athena.connector.lambda.QueryStatusChecker;
import com.amazonaws.athena.connector.lambda.ThrottlingInvoker;
import com.amazonaws.athena.connector.lambda.data.Block;
import com.amazonaws.athena.connector.lambda.data.BlockSpiller;
import com.amazonaws.athena.connector.lambda.domain.Split;
import com.amazonaws.athena.connector.lambda.domain.TableName;
import com.amazonaws.athena.connector.lambda.domain.predicate.Constraints;
import com.amazonaws.athena.connector.lambda.domain.predicate.QueryPlan;
import com.amazonaws.athena.connector.lambda.domain.predicate.Range;
import com.amazonaws.athena.connector.lambda.domain.predicate.SortedRangeSet;
import com.amazonaws.athena.connector.lambda.domain.predicate.ValueSet;
import com.amazonaws.athena.connector.lambda.handlers.RecordHandler;
import com.amazonaws.athena.connector.lambda.records.ReadRecordsRequest;
import com.amazonaws.athena.connector.substrait.SubstraitFunctionParser;
import com.amazonaws.athena.connector.substrait.SubstraitMetadataParser;
import com.amazonaws.athena.connector.substrait.SubstraitRelUtils;
import com.amazonaws.athena.connector.substrait.model.ColumnPredicate;
import com.amazonaws.athena.connector.substrait.model.SubstraitRelModel;
import com.amazonaws.athena.connectors.cloudwatch.qpt.CloudwatchQueryPassthrough;
import io.substrait.proto.Plan;
import org.apache.arrow.util.VisibleForTesting;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import software.amazon.awssdk.awscore.AwsRequestOverrideConfiguration;
import software.amazon.awssdk.services.athena.AthenaClient;
import software.amazon.awssdk.services.cloudwatchlogs.CloudWatchLogsClient;
import software.amazon.awssdk.services.cloudwatchlogs.model.GetLogEventsRequest;
import software.amazon.awssdk.services.cloudwatchlogs.model.GetLogEventsResponse;
import software.amazon.awssdk.services.cloudwatchlogs.model.GetQueryResultsResponse;
import software.amazon.awssdk.services.cloudwatchlogs.model.OutputLogEvent;
import software.amazon.awssdk.services.cloudwatchlogs.model.ResultField;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.secretsmanager.SecretsManagerClient;

import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeoutException;
import java.util.concurrent.atomic.AtomicLong;

import static com.amazonaws.athena.connectors.cloudwatch.CloudwatchExceptionFilter.EXCEPTION_FILTER;
import static com.amazonaws.athena.connectors.cloudwatch.CloudwatchMetadataHandler.LOG_GROUP_FIELD;
import static com.amazonaws.athena.connectors.cloudwatch.CloudwatchMetadataHandler.LOG_MSG_FIELD;
import static com.amazonaws.athena.connectors.cloudwatch.CloudwatchMetadataHandler.LOG_STREAM_FIELD;
import static com.amazonaws.athena.connectors.cloudwatch.CloudwatchMetadataHandler.LOG_TIME_FIELD;
import static com.amazonaws.athena.connectors.cloudwatch.CloudwatchUtils.getResult;

/**
 * Handles data read record requests for the Athena Cloudwatch Connector.
 * <p>
 * For more detail, please see the module's README.md, some notable characteristics of this class include:
 * <p>
 * 1. Reads and maps Cloudwatch Logs data for a specific LogStream (split)
 * 2. Attempts to push down time range predicates into Cloudwatch.
 */
public class CloudwatchRecordHandler
        extends RecordHandler
{
    private static final Logger logger = LoggerFactory.getLogger(CloudwatchRecordHandler.class);
    //Used to tag log lines generated by this connector for diagnostic purposes when interacting with Athena.
    private static final String SOURCE_TYPE = "cloudwatch";
    //Used to handle Throttling events and apply AIMD congestion control
    private final ThrottlingInvoker invoker;
    private final AtomicLong count = new AtomicLong(0);
    private final CloudWatchLogsClient awsLogs;
    private final CloudwatchQueryPassthrough queryPassthrough = new CloudwatchQueryPassthrough();

    public CloudwatchRecordHandler(java.util.Map<String, String> configOptions)
    {
        this(
                S3Client.create(),
                SecretsManagerClient.create(),
                AthenaClient.create(),
                CloudWatchLogsClient.create(),
                configOptions);
    }

    @VisibleForTesting
    protected CloudwatchRecordHandler(S3Client amazonS3, SecretsManagerClient secretsManager, AthenaClient athena, CloudWatchLogsClient awsLogs, java.util.Map<String, String> configOptions)
    {
        super(amazonS3, secretsManager, athena, SOURCE_TYPE, configOptions);
        this.awsLogs = awsLogs;
        this.invoker = ThrottlingInvoker.newDefaultBuilder(EXCEPTION_FILTER, configOptions).build();
    }

    /**
     * Scans Cloudwatch Logs using the LogStream and optional Time stamp filters.
     *
     * @see RecordHandler
     */
    @Override
    protected void readWithConstraint(BlockSpiller spiller, ReadRecordsRequest recordsRequest, QueryStatusChecker queryStatusChecker)
            throws TimeoutException, InterruptedException
    {
        // Managed-connector (Athena federation) path: apply the customer FAS credentials carried in
        // configOptions to every Cloudwatch data-plane call. Null (no-op) on the AppFlow/DNA path,
        // where the injected client already holds the customer credentials.
        AwsRequestOverrideConfiguration overrideConfig = getRequestOverrideConfig(recordsRequest.getIdentity().getConfigOptions());
        if (recordsRequest.getConstraints().isQueryPassThrough()) {
            getQueryPassthreoughResults(spiller, recordsRequest, overrideConfig);
        }
        else {
            String continuationToken = null;
            TableName tableName = recordsRequest.getTableName();
            Split split = recordsRequest.getSplit();
            invoker.setBlockSpiller(spiller);
            do {
                final String actualContinuationToken = continuationToken;
                GetLogEventsResponse logEventsResponse = invoker.invoke(() -> awsLogs.getLogEvents(
                        pushDownConstraints(recordsRequest.getConstraints(),
                                GetLogEventsRequest.builder()
                                        .logGroupName(split.getProperty(LOG_GROUP_FIELD))
                                        //We use the property instead of the table name because of the special all_streams table
                                        .logStreamName(split.getProperty(LOG_STREAM_FIELD))
                                        .nextToken(actualContinuationToken)
                                        // must be set to use nextToken correctly
                                        .startFromHead(true)
                                        .overrideConfiguration(overrideConfig)
                                        .build()
                        )));

                if (continuationToken == null || !continuationToken.equals(logEventsResponse.nextForwardToken())) {
                    continuationToken = logEventsResponse.nextForwardToken();
                }
                else {
                    continuationToken = null;
                }

                for (OutputLogEvent ole : logEventsResponse.events()) {
                    spiller.writeRows((Block block, int rowNum) -> {
                        boolean matched = true;
                        matched &= block.offerValue(LOG_STREAM_FIELD, rowNum, split.getProperty(LOG_STREAM_FIELD));
                        matched &= block.offerValue(LOG_TIME_FIELD, rowNum, ole.timestamp());
                        matched &= block.offerValue(LOG_MSG_FIELD, rowNum, ole.message());
                        return matched ? 1 : 0;
                    });
                }

                logger.info("readWithConstraint: LogGroup[{}] LogStream[{}] Continuation[{}] rows[{}]",
                        tableName.getSchemaName(), tableName.getTableName(), continuationToken,
                        logEventsResponse.events().size());
            }
            while (continuationToken != null && queryStatusChecker.isQueryRunning());
        }
    }

    private void getQueryPassthreoughResults(BlockSpiller spiller, ReadRecordsRequest recordsRequest,
            AwsRequestOverrideConfiguration awsRequestOverrideConfiguration) throws TimeoutException, InterruptedException
    {
        Map<String, String> qptArguments = recordsRequest.getConstraints().getQueryPassthroughArguments();
        queryPassthrough.verify(qptArguments);
        GetQueryResultsResponse getQueryResultsResponse = getResult(invoker, awsLogs, qptArguments, Integer.parseInt(qptArguments.get(CloudwatchQueryPassthrough.LIMIT)), awsRequestOverrideConfiguration);

        for (List<ResultField> resultList : getQueryResultsResponse.results()) {
            spiller.writeRows((Block block, int rowNum) -> {
                for (ResultField resultField : resultList) {
                    boolean matched = true;
                    matched &= block.offerValue(resultField.field(), rowNum, resultField.value());
                    if (!matched) {
                        return 0;
                    }
                }
                return 1;
            });
        }
    }

    /**
     * Attempts to push down predicates into Cloudwatch Logs by decorating the Cloudwatch Logs request.
     *
     * @param constraints The constraints for the read as provided by Athena based on the customer's query.
     * @param request     The Cloudwatch Logs request to inject predicates to.
     * @return The decorated Cloudwatch Logs request.
     * @note This impl currently only pushing down SortedRangeSet filters (>=, =<, between) on the log time column.
     */
    private GetLogEventsRequest pushDownConstraints(Constraints constraints, GetLogEventsRequest request)
    {
        GetLogEventsRequest.Builder requestBuilder = request.toBuilder();

        // Managed-connector (Athena federation) path: predicates arrive as a Substrait query plan rather
        // than in the Constraints summary. We push ONLY the log time range (>=, <=, =, between) down to
        // Cloudwatch as startTime/endTime. Any other predicate (message/log_stream filters, etc.) has no
        // GetLogEvents equivalent and is safely left for the engine to apply. If the plan cannot be
        // parsed or contains operators we do not understand, we push nothing and let the engine filter.
        if (constraints.getQueryPlan() != null) {
            applySubstraitTimeRange(constraints, requestBuilder);
            return requestBuilder.build();
        }

        ValueSet timeConstraint = constraints.getSummary().get(LOG_TIME_FIELD);
        if (timeConstraint instanceof SortedRangeSet && !timeConstraint.isNullAllowed()) {
            //SortedRangeSet is how >, <, between is represented which are easiest and most common when
            //searching logs so we attempt to push that down here as an optimization. SQL can represent complex
            //overlapping ranges which Cloudwatch can not support so this is not a replacement for applying
            //constraints using the ConstraintEvaluator.

            Range basicPredicate = ((SortedRangeSet) timeConstraint).getSpan();

            if (!basicPredicate.getLow().isNullValue()) {
                Long lowerBound = (Long) basicPredicate.getLow().getValue();
                requestBuilder.startTime(lowerBound);
            }

            if (!basicPredicate.getHigh().isNullValue()) {
                Long upperBound = (Long) basicPredicate.getHigh().getValue();
                requestBuilder.endTime(upperBound);
            }
        }

        return requestBuilder.build();
    }

    /**
     * Extracts predicates on the log {@code time} column from the Substrait query plan and pushes them to
     * Cloudwatch as {@code startTime}/{@code endTime}. This is a best-effort optimization: it never throws.
     * Unsupported operators or plan shapes result in no pushdown, leaving all predicates for the engine to
     * apply (federation permits returning a superset).
     *
     * @param constraints the read constraints, expected to carry a non-null Substrait query plan.
     * @param requestBuilder the Cloudwatch GetLogEvents request builder to decorate with time bounds.
     */
    private void applySubstraitTimeRange(Constraints constraints, GetLogEventsRequest.Builder requestBuilder)
    {
        QueryPlan queryPlan = constraints.getQueryPlan();
        if (queryPlan == null || queryPlan.getSubstraitPlan() == null) {
            return;
        }
        try {
            Plan plan = SubstraitRelUtils.deserializeSubstraitPlan(queryPlan.getSubstraitPlan());
            SubstraitRelModel relModel = SubstraitRelModel.buildSubstraitRelModel(plan.getRelations(0).getRoot().getInput());
            if (relModel.getFilterRel() == null) {
                return;
            }
            List<String> tableColumns = SubstraitMetadataParser.getTableColumns(relModel);
            Map<String, List<ColumnPredicate>> predicatesByColumn = SubstraitFunctionParser.getColumnPredicatesMap(
                    plan.getExtensionsList(), relModel.getFilterRel().getCondition(), tableColumns);

            for (ColumnPredicate predicate : predicatesByColumn.getOrDefault(LOG_TIME_FIELD, List.of())) {
                Object value = predicate.getValue();
                if (!(value instanceof Number)) {
                    continue;
                }
                long epochMillis = ((Number) value).longValue();
                switch (predicate.getOperator()) {
                    case GREATER_THAN:
                    case GREATER_THAN_OR_EQUAL_TO:
                        requestBuilder.startTime(epochMillis);
                        break;
                    case LESS_THAN:
                    case LESS_THAN_OR_EQUAL_TO:
                        requestBuilder.endTime(epochMillis);
                        break;
                    case EQUAL:
                        requestBuilder.startTime(epochMillis);
                        requestBuilder.endTime(epochMillis);
                        break;
                    default:
                        // No GetLogEvents equivalent (e.g. NOT_EQUAL / IS_NULL); leave to the engine.
                        break;
                }
            }
        }
        catch (Exception e) {
            // Best-effort pushdown only: never fail the query. If the plan contains operators or shapes
            // we do not understand, skip pushdown and let the engine apply all predicates.
            logger.warn("Unable to push Substrait time-range predicate to Cloudwatch; leaving predicates to the engine.", e);
        }
    }
}
