Transform: 'AWS::Serverless-2016-10-31'
Metadata:
  'AWS::ServerlessRepo::Application':
    Name: AthenaTimestreamConnectorWithGlueConnection
    Description: 'This connector enables Amazon Athena to communicate with Amazon Timestream, making your time series data accessible from Athena.'
    Author: 'default author'
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels:
      - athena-federation
    HomePageUrl: 'https://github.com/awslabs/aws-athena-query-federation'
    SemanticVersion: 2022.47.1
    SourceCodeUrl: 'https://github.com/awslabs/aws-athena-query-federation'
Parameters:
  LambdaFunctionName:
    Description: 'This is the name of the lambda function that will be created. This name must satisfy the pattern ^[a-z0-9-_]{1,64}$'
    Type: String
    AllowedPattern: ^[a-z0-9-_]{1,64}$
  SpillBucket:
    Description: 'The name of the bucket where this function can spill data.'
    Type: String
  GlueConnection:
    Description: "Name of glue connection storing connection details for Federated Data source."
    Type: String
  KmsKeyId:
    Description: "(Optional) By default any data that is spilled to S3 is encrypted using AES-GCM and a randomly generated key. Setting a KMS Key ID allows your Lambda function to use KMS for key generation for a stronger source of encryption keys."
    Type: String
    Default: ""
  LambdaRoleArn:
    Description: "(Optional) A custom role to be used by the Connector lambda"
    Type: String
    Default: ""
  GlueGammaRegion:
    Description: "(Optional) Region for testing connections in Glue Gamma farm. Required to be all lower case, ex: 'us-east-1', 'ap-south-1'."
    Type: String
    Default: ""

Conditions:
  NotHasLambdaRole: !Equals [!Ref LambdaRoleArn, ""]
  HasKMSKeyId: !Not [!Equals [!Ref KmsKeyId, ""]]
  NotHasLambdaRoleAndHasKMSKeyId: !And
    - !Condition NotHasLambdaRole
    - !Condition HasKMSKeyId
  HasGlueGammaRegion: !Not [ !Equals [!Ref GlueGammaRegion, ""] ]

Resources:
  ConnectorConfig:
    Type: 'AWS::Serverless::Function'
    Properties:
      Environment:
        Variables:
          glue_connection: !Ref GlueConnection
          gamma_glue_region: !If [ HasGlueGammaRegion, !Ref GlueGammaRegion, !Ref "AWS::NoValue" ]
      FunctionName: !Ref LambdaFunctionName
      Handler: "com.amazonaws.athena.connectors.timestream.TimestreamCompositeHandler"
      CodeUri: "./target/athena-timestream-2022.47.1.jar"
      Description: "Enables Amazon Athena to communicate with Amazon Timestream, making your time series data accessible from Athena."
      Runtime: java11
      Timeout: 900
      MemorySize: 3008
      Role: !If [NotHasLambdaRole, !GetAtt FunctionRole.Arn, !Ref LambdaRoleArn]

  FunctionRole:
    Condition: NotHasLambdaRole
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
                - "sts:AssumeRole"
      Policies:
        #S3CrudPolicy allows our connector to spill large responses to S3. You can optionally replace this pre-made policy
        #with one that is more restrictive and can only 'put' but not read,delete, or overwrite files.
        - S3CrudPolicy:
            BucketName: !Ref SpillBucket
                  
  FunctionExecutionPolicy:
    Condition: NotHasLambdaRole
    Type: "AWS::IAM::Policy"
    Properties:
      Roles:
        - !Ref FunctionRole
      PolicyName: FunctionExecutionPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - glue:GetTableVersions
              - glue:GetPartitions
              - glue:GetTables
              - glue:GetTableVersion
              - glue:GetDatabases
              - glue:GetTable
              - glue:GetPartition
              - glue:GetDatabase
              - athena:GetQueryExecution
              - s3:ListAllMyBuckets
              - timestream:Describe*
              - timestream:List*
              - timestream:Select*
            Effect: Allow
            Resource: '*'
          - Action:
            - glue:GetConnection
            Effect: Allow
            Resource:
              - Fn::Sub:
                - 'arn:${AWS::Partition}:glue:${Region}:${AWS::AccountId}:connection/${GlueConnection}'
                - Region: !If [ HasGlueGammaRegion, !Ref GlueGammaRegion, !Ref "AWS::Region" ]
              - Fn::Sub: 
                - 'arn:${AWS::Partition}:glue:${Region}:${AWS::AccountId}:catalog'
                - Region: !If [ HasGlueGammaRegion, !Ref GlueGammaRegion, !Ref "AWS::Region" ]

  FunctionKMSPolicy:
    Condition: NotHasLambdaRoleAndHasKMSKeyId
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: FunctionKMSPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
             - kms:GenerateRandom
            Resource: '*'
          - Effect: Allow
            Action:
              - kms:GenerateDataKey
            Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsKeyId}"
      Roles:
        - !Ref FunctionRole