Transform: 'AWS::Serverless-2016-10-31'
Metadata:
  'AWS::ServerlessRepo::Application':
    Name: AthenaSqlServerConnectorWithGlueConnection
    Description: 'This connector enables Amazon Athena to communicate with SQL Server using JDBC driver.'
    Author: 'default author'
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels:
      - sqlserver
      - athena-federation
      - jdbc
    HomePageUrl: 'https://github.com/awslabs/aws-athena-query-federation'
    SemanticVersion: 2022.47.1
    SourceCodeUrl: 'https://github.com/awslabs/aws-athena-query-federation'
Parameters:
  LambdaFunctionName:
    Description: 'This is the name of the lambda function that will be created. This name must satisfy the pattern ^[a-z0-9-_]{1,64}$'
    Type: String
    AllowedPattern: ^[a-z0-9-_]{1,64}$
  SecretName:
    Description: 'Used to create resource-based authorization policy for "secretsmanager:GetSecretValue" action. E.g. All Athena JDBC Federation secret names can be prefixed with "AthenaJdbcFederation" and authorization policy will allow "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:AthenaJdbcFederation*". Parameter value in this case should be "AthenaJdbcFederation". If you do not have a prefix, you can manually update the IAM policy to add allow any secret names.'
    Type: String
  SpillBucket:
    Description: 'The name of the bucket where this function can spill data.'
    Type: String
  SecurityGroupIds:
    Description: '(Optional) One or more SecurityGroup IDs corresponding to the SecurityGroup that should be applied to the Lambda function. (e.g. sg1,sg2,sg3)'
    Type: CommaDelimitedList
    Default: ""
  SubnetIds:
    Description: '(Optional) One or more Subnet IDs corresponding to the Subnet that the Lambda function can use to access you data source. (e.g. subnet1,subnet2)'
    Type: CommaDelimitedList
    Default: ""
  GlueConnection:
    Description: "Name of glue connection storing connection details for Federated Data source."
    Type: String
  KmsKeyId:
    Description: "(Optional) By default any data that is spilled to S3 is encrypted using AES-GCM and a randomly generated key. Setting a KMS Key ID allows your Lambda function to use KMS for key generation for a stronger source of encryption keys."
    Type: String
    Default: ""
  LambdaRoleArn:
    Description: "(Optional) A custom role to be used by the Connector lambda"
    Type: String
    Default: ""
  GlueGammaRegion:
    Description: "(Optional) Region for testing connections in Glue Gamma farm. Required to be all lower case, ex: 'us-east-1', 'ap-south-1'."
    Type: String
    Default: ""

Conditions:
  NotHasLambdaRole: !Equals [!Ref LambdaRoleArn, ""]
  HasKMSKeyId: !Not [!Equals [!Ref KmsKeyId, ""]]
  NotHasLambdaRoleAndHasKMSKeyId: !And
    - !Condition NotHasLambdaRole
    - !Condition HasKMSKeyId
  HasSecurityGroups: !Not [ !Equals [ !Join ["", !Ref SecurityGroupIds], "" ] ]
  HasSubnets: !Not [ !Equals [ !Join ["", !Ref SubnetIds], "" ] ]
  HasGlueGammaRegion: !Not [ !Equals [!Ref GlueGammaRegion, ""] ]

Resources:
  JdbcConnectorConfig:
    Type: 'AWS::Serverless::Function'
    Properties:
      Environment:
        Variables:
          glue_connection: !Ref GlueConnection
          gamma_glue_region: !If [ HasGlueGammaRegion, !Ref GlueGammaRegion, !Ref "AWS::NoValue" ]
      FunctionName: !Ref LambdaFunctionName
      Handler: "com.amazonaws.athena.connectors.sqlserver.SqlServerCompositeHandler"
      CodeUri: "./target/athena-sqlserver-2022.47.1.jar"
      Description: "Enables Amazon Athena to communicate with SQLSERVER using JDBC"
      Runtime: java11
      Timeout: 900
      MemorySize: 3008
      Role: !If [NotHasLambdaRole, !GetAtt FunctionRole.Arn, !Ref LambdaRoleArn]
      VpcConfig:
        SecurityGroupIds: !If [ HasSecurityGroups, !Ref SecurityGroupIds, !Ref "AWS::NoValue" ]
        SubnetIds: !If [ HasSubnets, !Ref SubnetIds, !Ref "AWS::NoValue" ]

  FunctionRole:
    Condition: NotHasLambdaRole
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
                - "sts:AssumeRole"

  FunctionExecutionPolicy:
    Condition: NotHasLambdaRole
    Type: "AWS::IAM::Policy"
    Properties:
      Roles:
        - !Ref FunctionRole
      PolicyName: FunctionExecutionPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - glue:GetConnection
            Effect: Allow
            Resource:
              - !Sub 'arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:connection/${GlueConnection}'
              - !Sub 'arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:catalog'
          - Action:
              - secretsmanager:GetSecretValue
            Effect: Allow
            Resource: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*'
          - Action:
              - logs:CreateLogGroup
            Effect: Allow
            Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*'
          - Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionName}:*'
          - Action:
            - athena:GetQueryExecution
            - s3:ListAllMyBuckets
            Effect: Allow
            Resource: '*'
          - Action:
            - ec2:CreateNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DetachNetworkInterface
            Effect: Allow
            Resource: '*'
          - Action:
             - s3:GetObject
             - s3:ListBucket
             - s3:GetBucketLocation
             - s3:GetObjectVersion
             - s3:PutObject
             - s3:PutObjectAcl
             - s3:GetLifecycleConfiguration
             - s3:PutLifecycleConfiguration
             - s3:DeleteObject
            Effect: Allow
            Resource:
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}
                - bucketName:
                    Ref: SpillBucket
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}/*
                - bucketName:
                    Ref: SpillBucket
          - Action:
            - glue:GetConnection
            Effect: Allow
            Resource:
              - Fn::Sub:
                - 'arn:${AWS::Partition}:glue:${Region}:${AWS::AccountId}:connection/${GlueConnection}'
                - Region: !If [ HasGlueGammaRegion, !Ref GlueGammaRegion, !Ref "AWS::Region" ]
              - Fn::Sub:
                - 'arn:${AWS::Partition}:glue:${Region}:${AWS::AccountId}:catalog'
                - Region: !If [ HasGlueGammaRegion, !Ref GlueGammaRegion, !Ref "AWS::Region" ]

  FunctionKMSPolicy:
    Condition: NotHasLambdaRoleAndHasKMSKeyId
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: FunctionKMSPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
             - kms:GenerateRandom
            Resource: '*'
          - Effect: Allow
            Action:
              - kms:GenerateDataKey
            Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsKeyId}"
      Roles:
        - !Ref FunctionRole