version = 0.1
[default.deploy.parameters]
stack_name = "oracle-test-aimethed"
resolve_s3 = true
s3_prefix = "oracle-test-aimethed"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "LambdaFunctionName=\"oracle-test-aimethed\" DefaultConnectionString=\"jdbc:oracle:thin:${rds!db-e2376c2c-2d25-451a-a3eb-5446695f9c7c}@//markcoh-oracle-database-1.cxwou8w6kmpz.us-west-2.rds.amazonaws.com:1521/ORCL\" SecretNamePrefix=\"*\" IsFIPSEnabled=\"false\" SpillBucket=\"athena-s3-output-bucket-01\" SpillPrefix=\"athena-spill\" LambdaTimeout=\"900\" LambdaMemory=\"3008\" LambdaRoleARN=\"\" DisableSpillEncryption=\"false\" SecurityGroupIds=\"sg-0ca2865e51e85b116\" SubnetIds=\"subnet-0be0d7a5c4a61fa0f\" PermissionsBoundaryARN=\"\""
image_repositories = []
