/*-
 * #%L
 * Amazon Athena Query Federation Integ Test
 * %%
 * Copyright (C) 2019 - 2020 Amazon Web Services
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package com.amazonaws.athena.connector.integ;

import com.amazonaws.athena.connector.integ.data.ConnectorVpcAttributes;
import com.amazonaws.athena.connector.integ.providers.ConnectorVpcAttributesProvider;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import software.amazon.awscdk.core.App;
import software.amazon.awscdk.core.Stack;
import software.amazon.awscdk.services.iam.PolicyDocument;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

/**
 * Responsible for providing a CloudFormation stack template for the connector being tested.
 */
public abstract class CloudFormationTemplateProvider
{
    private static final Logger logger = LoggerFactory.getLogger(CloudFormationTemplateProvider.class);

    private static final int LAMBDA_FUNCTION_MAX_LENGTH = 64;

    private final String cloudFormationStackName;
    private final Map<String, Object> testConfig;
    private final App theApp;
    private final ObjectMapper objectMapper;
    private final String lambdaFunctionName;
    private final Optional<ConnectorVpcAttributes> vpcAttributes;

    public CloudFormationTemplateProvider(String stackName, Map<String, Object> testConfig)
    {
        final String randomUuidStr = UUID.randomUUID().toString();
        theApp = new App();
        objectMapper = new ObjectMapper().configure(SerializationFeature.INDENT_OUTPUT, true);
        cloudFormationStackName = String.format("integration-%s-%s", stackName, randomUuidStr);
        // Lambda Function's name cannot exceed 64 bytes.
        lambdaFunctionName = String.format("%s_%s", stackName.toLowerCase(), randomUuidStr
                .replace('-', '_'))
                .substring(0, Math.min(LAMBDA_FUNCTION_MAX_LENGTH, stackName.length() + randomUuidStr.length() + 1));
        this.testConfig = testConfig;
        vpcAttributes = ConnectorVpcAttributesProvider.getAttributes(this.testConfig);
    }

    /**
     * Must be overridden to facilitate getting the lambda function's IAM access policy. The latter sets up
     * access to multiple connector-specific AWS services (e.g. DynamoDB, Elasticsearch etc...)
     * @return A policy document object.
     */
    protected abstract Optional<PolicyDocument> getAccessPolicy();

    /**
     * Must be overridden to facilitate the setting of the lambda function's environment variables key-value pairs
     * (e.g. "spill_bucket":"myspillbucket"). See individual connector for expected environment variables. This method
     * can be a no-op in the extending class since some environment variables are set by default (spill_bucket,
     * spill_prefix, and disable_spill_encryption).
     */
    protected abstract void setEnvironmentVars(final Map environmentVars);

    /**
     * Must be overridden (can be a no-op) to facilitate the creation of a connector-specific CloudFormation stack
     * resource (e.g. DB table) using AWS CDK.
     * @param stack The current CloudFormation stack.
     */
    protected abstract void setSpecificResource(final Stack stack);

    /**
     * Gets the CloudFormation stack name.
     * @return The stack's name.
     */
    protected String getStackName()
    {
        return cloudFormationStackName;
    }

    /**
     * Gets the name of the lambda function generated by the Integration-Test module.
     * @return The name of the lambda function.
     */
    protected String getLambdaFunctionName()
    {
        return lambdaFunctionName;
    }

    /**
     * Gets the VPC attributes used in generating the lambda function.
     * @return The VPC attributes object.
     */
    protected Optional<ConnectorVpcAttributes> getVpcAttributes()
    {
        return vpcAttributes;
    }

    /**
     * Gets the CloudFormation stack template.
     * @return The stack template as String.
     */
    protected String getTemplate()
    {
        return generateTemplate();
    }

    /**
     * Gets the CloudFormation template (generated programmatically using AWS CDK).
     * @return CloudFormation stack template.
     */
    private String generateTemplate()
    {
        final Stack stack = generateStack();
        final String stackTemplate = objectMapper
                .valueToTree(theApp.synth().getStackArtifact(stack.getArtifactId()).getTemplate())
                .toPrettyString();
        logger.info("CloudFormation Template:\n{}: {}", cloudFormationStackName, stackTemplate);

        return stackTemplate;
    }

    /**
     * Generate the CloudFormation stack programmatically using AWS CDK.
     * @return CloudFormation stack object.
     */
    private Stack generateStack()
    {
        ConnectorStackAttributesProvider attributesProvider = new ConnectorStackAttributesProvider(theApp,
                cloudFormationStackName, lambdaFunctionName, testConfig, getAccessPolicy(), getEnvironmentVars(),
                vpcAttributes);
        ConnectorStackFactory stackFactory = new ConnectorStackFactory(attributesProvider.getAttributes());
        final Stack stack = stackFactory.createStack();
        setSpecificResource(stack);

        return stack;
    }

    /**
     * Gets the specific connectors' environment variables.
     * @return A Map containing the environment variables key-value pairs.
     */
    private Map<String, String> getEnvironmentVars()
    {
        final Map<String, String> environmentVars = new HashMap<>();
        // Set connector-specific environment variables.
        setEnvironmentVars(environmentVars);

        return environmentVars;
    }
}
